In [1]:
%load_ext autoreload
%autoreload 2

from context import uncertify

In [2]:
import logging
from uncertify.log import setup_logging
setup_logging()
LOG = logging.getLogger(__name__)

# Matplotlib DEBUG logging spits out a whole bunch of crap
mpl_logger = logging.getLogger('matplotlib')
mpl_logger.setLevel(logging.WARNING)

In [3]:
import nibabel as nib

In [4]:
img = nib.load('/mnt/2TB_internal_HD/datasets/raw/IXI/T2w/IXI016-Guys-0697-T2.nii.gz')

In [6]:
print(img)

<class 'nibabel.nifti1.Nifti1Image'>
data shape (256, 256, 120)
affine: 
[[-9.35355961e-01 -6.33208156e-02 -3.00818309e-03  1.35962814e+02]
 [-6.02702796e-02  8.99803102e-01 -3.27911258e-01 -9.63707962e+01]
 [-1.95586868e-02  2.55444378e-01  1.15432215e+00 -6.42896881e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 256 256 120   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [-1.          0.93749976  0.9375004   1.1999977   0.          0.
  0.          0.        ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units     

In [ ]:
from uncertify.models.utils import conv2d_output_shape, convtranspose2d_output_shape
from uncertify.models.encoder_decoder_baur2020 import BaurEncoder, BaurDecoder
from uncertify.models.vae import VariationalAutoEncoder

In [ ]:
VariationalAutoEncoder(BaurEncoder(), BaurDecoder())

In [ ]:
from torch import nn

In [ ]:
from uncertify.models.baur_small import BaurEncoderSmall, BaurDecoderSmall, print_feature_map_sizes_baur_small
from uncertify.models.encoder_decoder_baur2020 import print_feature_map_sizes_baur
from uncertify.evaluation.inference import yiel

In [ ]:
print_feature_map_sizes_baur()

In [ ]:
print_feature_map_sizes_baur_small()

In [ ]:
VariationalAutoEncoder(BaurEncoderSmall(), BaurDecoderSmall())

In [ ]:
from dataclasses import dataclass

In [ ]:
@dataclass
class A:
    a1 = 1
        
class B:
    b1 = 10
    a = A()

In [ ]:
d = {'one': Test(), 'two': Test()}

In [ ]:
d['one'].a = 10

In [ ]:
d['two'].a

In [ ]:
d['one'].a

In [ ]:
b1 = B()
b2 = B()

In [ ]:
id(b1.a)

In [ ]:
id(b2.a)

In [ ]:
from uncertify.models.beta_annealing import plot_annealing_schedules

In [ ]:
plot_annealing_schedules(n_train_steps=50000, cycle_size=10000)

In [ ]:
a = [1, 2, 3]

In [ ]:
from enum import Enum

In [ ]:
class A(Enum):
    A1 = 1
    A2 = 2


In [ ]:
A.A1.name

In [ ]:
from collections import defaultdict

In [ ]:
d = defaultdict(dict)

In [ ]:
d[1][2] = 2

In [ ]:
d

In [ ]:
import numpy as np

In [ ]:
np.ones(10, dtype=bool)

In [ ]:
import torch

In [ ]:
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

In [ ]:
torch.sum(t, dim=1)

In [ ]:
import torch

In [ ]:
t = torch.tensor([[[[1., 2.],
                   [3., 4.]]],
                  [[[5., 6.],
                   [7., 8.]]],
                  [[[9., 10.],
                   [11., 15.]]]])
print(t.shape)

In [ ]:
n = torch.zeros_like(t)
for slice_idx, img in enumerate(t):
    s = torch.softmax(img[0].flatten(), dim=0)
    i = torch.reshape(s, shape=(2, 2))
    n[slice_idx][0] = i

In [ ]:
print(n)